### PR TITLE
Issue #3: Changing entity creation to use the correct enttity classes…

### PR DESCRIPTION
**Pull request by hosef**
… instead of standard objects.

### CODE REVIEW

**Comment by hosef** [comment]
I accidentally used the wrong issue number in the commit message. I meant to reference #7.

**Review by Graham-72 — CHANGES_REQUESTED** [review]
I believe line 57 of `bulk_media_upload.summary.inc` also needs a 'language' changed to 'langcode' so that it becomes

`  $multilanguage = (module_exists('translation') || db_query_range("SELECT 1 FROM {node} WHERE langcode <> :language", 0, 1, array(':language' => LANGUAGE_NONE))->fetchField());
`

**Comment by hosef** [comment]
@Graham-72 I have made the change that you requested.

**Comment by Graham-72** [comment]
@hosef thank you for this.

**Pull request merged**
